In [1]:
import tensorflow as tf

Constants

In [2]:
a = tf.constant(7)
b = tf.constant(5)

c = a+b
c

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [3]:
type(a),print(a)

tf.Tensor(7, shape=(), dtype=int32)


(tensorflow.python.framework.ops.EagerTensor, None)

In [4]:
print(c),type(c)

tf.Tensor(12, shape=(), dtype=int32)


(None, tensorflow.python.framework.ops.EagerTensor)

In [5]:
matriz_constant = tf.constant([[1,2,3,4],[5,6,7,8]],name='matriz const')
print(matriz_constant)

tf.Tensor(
[[1 2 3 4]
 [5 6 7 8]], shape=(2, 4), dtype=int32)


In [6]:
string_constant_1 = tf.constant('Text 1')
string_constant_2 = tf.constant('Text 2')
string_constant_1,string_constant_2

(<tf.Tensor: shape=(), dtype=string, numpy=b'Text 1'>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'Text 2'>)

In [7]:
type(string_constant_1)
check = string_constant_1+string_constant_2

In [8]:
print(string_constant_1.numpy()),check.numpy()

b'Text 1'


(None, b'Text 1Text 2')

Variables

In [9]:
x = tf.Variable(10)
y = x + 35
print(y)

tf.Tensor(45, shape=(), dtype=int32)


In [10]:
x.assign(56)
print(x,x+70)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=56> tf.Tensor(126, shape=(), dtype=int32)


In [11]:
for i in range(5):
    x = x+4
    print(x.numpy())

60
64
68
72
76


Addition of vectors and matrices

In [12]:
a = tf.constant([[1,2,3],[2,5,6]],name='first')
b = tf.constant([[2,3,4],[5,6,7]],name='second')

c = a + b
d = a*b

In [13]:
print(c)

tf.Tensor(
[[ 3  5  7]
 [ 7 11 13]], shape=(2, 3), dtype=int32)


In [14]:
print(d)

tf.Tensor(
[[ 2  6 12]
 [10 30 42]], shape=(2, 3), dtype=int32)


In [15]:
f = tf.constant([1,2,3,4])
g = tf.constant([2,3,4,5])

h = f+g
i = f*g

In [16]:
print(h,i)

tf.Tensor([3 5 7 9], shape=(4,), dtype=int32) tf.Tensor([ 2  6 12 20], shape=(4,), dtype=int32)


In [17]:
check = tf.add(f,g)
print(check)

tf.Tensor([3 5 7 9], shape=(4,), dtype=int32)


In [18]:
new_a = tf.constant([[1,2],[3,4]])
new_b = tf.constant([[-1,2],[4,5]])
multi = tf.matmul(new_a,new_b)
multi

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 12],
       [13, 26]])>

In [19]:
new_a_2 = tf.constant([[2,3],[0,1],[-1,4]])
new_b_2 = tf.constant([[1,2,3],[-2,0,4]])
multi_2 = tf.matmul(new_a_2,new_b_2)
multi_2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[-4,  4, 18],
       [-2,  0,  4],
       [-9, -2, 13]])>