In [263]:
import tensorflow as tf
import datetime
import os
from tensorflow import keras
import datetime

In [264]:
print(tf.__version__)

2.17.0


Others functions

In [265]:
x= tf.ones((3,3))
print(x)
y = tf.zeros((3,3))
print(y)
z = tf.eye((3))
print(z)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


Constants

In [266]:
a = tf.constant(7)
b = tf.constant(5)

c = a+b
c
d = tf.subtract(a,b)

In [267]:
type(a),print(a),print(d),print(a-b)

tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


(tensorflow.python.framework.ops.EagerTensor, None, None, None)

In [268]:
print(c),type(c)

tf.Tensor(12, shape=(), dtype=int32)


(None, tensorflow.python.framework.ops.EagerTensor)

In [269]:
matriz_constant = tf.constant([[1,2,3,4],[5,6,7,8]],name='matriz const')
print(matriz_constant)

tf.Tensor(
[[1 2 3 4]
 [5 6 7 8]], shape=(2, 4), dtype=int32)


In [270]:
string_constant_1 = tf.constant('Text 1')
string_constant_2 = tf.constant('Text 2')
string_constant_1,string_constant_2

(<tf.Tensor: shape=(), dtype=string, numpy=b'Text 1'>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'Text 2'>)

In [271]:
type(string_constant_1)
check = string_constant_1+string_constant_2

In [272]:
print(string_constant_1.numpy()),check.numpy()

b'Text 1'


(None, b'Text 1Text 2')

Variables

In [273]:
x = tf.Variable(10)
y = x + 35
print(y)

tf.Tensor(45, shape=(), dtype=int32)


In [274]:
x.assign(56)
print(x,x+70)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=56> tf.Tensor(126, shape=(), dtype=int32)


In [275]:
for i in range(5):
    x = x+4
    print(x.numpy())

60
64
68
72
76


Addition of vectors and matrices

In [276]:
a = tf.constant([[1,2,3],[2,5,6]],name='first')
b = tf.constant([[2,3,4],[5,6,7]],name='second')

c = a + b
d = a*b

In [277]:
print(c)

tf.Tensor(
[[ 3  5  7]
 [ 7 11 13]], shape=(2, 3), dtype=int32)


In [278]:
print(d)

tf.Tensor(
[[ 2  6 12]
 [10 30 42]], shape=(2, 3), dtype=int32)


In [279]:
f = tf.constant([1,2,3,4])
g = tf.constant([2,3,4,5])

h = f+g
i = f*g

result = tf.reduce_sum(i)
print(result)

tf.Tensor(40, shape=(), dtype=int32)


In [280]:
print(h,i)

tf.Tensor([3 5 7 9], shape=(4,), dtype=int32) tf.Tensor([ 2  6 12 20], shape=(4,), dtype=int32)


In [281]:
check = tf.add(f,g)
print(check)

tf.Tensor([3 5 7 9], shape=(4,), dtype=int32)


In [282]:
new_a = tf.constant([[1,2],[3,4]])
new_b = tf.constant([[-1,2],[4,5]])
multi = tf.matmul(new_a,new_b)
multi

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 12],
       [13, 26]])>

In [283]:
new_a_2 = tf.constant([[2,3],[0,1],[-1,4]])
new_b_2 = tf.constant([[1,2,3],[-2,0,4]])
multi_2 = tf.matmul(new_a_2,new_b_2)
multi_2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[-4,  4, 18],
       [-2,  0,  4],
       [-9, -2, 13]])>

Dot product

In [284]:
neuron = tf.constant([[-1.0,7.0,8.0]],name='neuron')
pounds = tf.constant([[0.8,0.1,0.]],name='pounds')

result = tf.multiply(neuron,pounds)

answer = tf.reduce_sum(result)

answer

<tf.Tensor: shape=(), dtype=float32, numpy=-0.100000024>

Grafos

In [285]:
def grafo_computation(x):
    x = x**2 + 2*x +2
    return x

In [286]:
x=tf.constant(5.0)

result = grafo_computation(5)

result

37

Tensorboard

In [287]:
# Load the TensorBoard notebook extension
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard


In [288]:
mnist = tf.keras.datasets.mnist
mnist

<module 'keras.api.datasets.mnist' from 'c:\\Users\\mbern\\OneDrive\\tensforFlow\\tensorFlowCourse\\.venv\\Lib\\site-packages\\keras\\api\\datasets\\mnist\\__init__.py'>

In [289]:
(x_train,y_train),(x_test,y_test) = mnist.load_data()

In [290]:
x_train,x_test = x_train/255.0,x_test/255.0

In [291]:
def create_model():
  return tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10, activation='softmax')
  ])

In [292]:
model = create_model()
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)

model.fit(x=x_train, 
          y=y_train, 
          epochs=5, 
          validation_data=(x_test, y_test), 
          callbacks=[tensorboard_callback])

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - accuracy: 0.8906 - loss: 0.3722 - val_accuracy: 0.9654 - val_loss: 0.1094
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - accuracy: 0.9676 - loss: 0.1037 - val_accuracy: 0.9765 - val_loss: 0.0787
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - accuracy: 0.9776 - loss: 0.0688 - val_accuracy: 0.9773 - val_loss: 0.0722
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 14s 7ms/step - accuracy: 0.9845 - loss: 0.0515 - val_accuracy: 0.9792 - val_loss: 0.0699
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.9869 - loss: 0.0414 - val_accuracy: 0.9784 - val_loss: 0.0748


In [293]:
%tensorboard --logdir logs/fit