In [46]:
import tensorflow as tf

In [47]:
tf.__version__

'2.17.0'

In [48]:
a = tf.constant([2],name='constant_a')
b = tf.constant([3],name='constant_b')

In [49]:
a

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([2])>

In [50]:
print(a.numpy()[0])

2


In [51]:
@tf.function
def add_(a,b):
    c = a + b
    print(c)
    return c

In [52]:
result = add_(a,b)
tf.print(result[0])

Tensor("add:0", shape=(1,), dtype=int32)
5


Defining multidimensional arrays using TensorFlow:
Now we will try to define such arrays using TensorFlow

In [53]:
Scalar = tf.constant(4)
Vector = tf.constant([5,6,4])
Matrix = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
Tensor = tf.constant([ [[1,2,3],[2,3,4],[3,4,5]] , [[4,5,6],[5,6,7],[6,7,8]] , [[7,8,9],[8,9,10],[9,10,11]] ])

In [54]:
print ("Scalar (1 entry):\n %s \n" % Scalar)

print ("Vector (3 entries) :\n %s \n" % Vector)

print ("Matrix (3x3 entries):\n %s \n" % Matrix)

print ("Tensor (3x3x3 entries) :\n %s \n" % Tensor)

Scalar (1 entry):
 tf.Tensor(4, shape=(), dtype=int32) 

Vector (3 entries) :
 tf.Tensor([5 6 4], shape=(3,), dtype=int32) 

Matrix (3x3 entries):
 tf.Tensor(
[[1 2 3]
 [2 3 4]
 [3 4 5]], shape=(3, 3), dtype=int32) 

Tensor (3x3x3 entries) :
 tf.Tensor(
[[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]], shape=(3, 3, 3), dtype=int32) 



In [55]:
Scalar.shape,Tensor.shape

(TensorShape([]), TensorShape([3, 3, 3]))

In [56]:
Matriz_one = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
Matriz_two = tf.constant([[2,2,2],[2,2,2],[2,2,2]])

In [57]:
@tf.function

def add_d():
    sum_matriz= tf.add(Matriz_one,Matriz_two)
    return sum_matriz

In [58]:
result_1 = add_d()
result_2 = Matriz_one+Matriz_two

print(result_1,result_2)

tf.Tensor(
[[3 4 5]
 [4 5 6]
 [5 6 7]], shape=(3, 3), dtype=int32) tf.Tensor(
[[3 4 5]
 [4 5 6]
 [5 6 7]], shape=(3, 3), dtype=int32)


In [60]:
Matriz_one = tf.constant([[2,3],[3,4]])
Matriz_two = tf.constant([[2,3],[3,4]])

print(Matriz_one)

@tf.function

def mathmul():
    result_mult = tf.matmul(Matriz_one,Matriz_two)
    return(result_mult)

result_1 = mathmul()
result_2 = Matriz_one*Matriz_two

print(result_1,result_2)

tf.Tensor(
[[2 3]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[13 18]
 [18 25]], shape=(2, 2), dtype=int32) tf.Tensor(
[[ 4  9]
 [ 9 16]], shape=(2, 2), dtype=int32)


Variables

In [61]:
v = tf.Variable(0)

In [62]:
@tf.function

def increase_one(v):
    v = tf.add(v,1)
    return v



In [63]:
for i in range(3):
    v = increase_one(v)
    print(v)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


Operations

In [64]:
a = tf.constant([5])
b = tf.constant([3])

c = tf.add(a,b)
d= tf.subtract(a,b)

print(c,d)

tf.Tensor([8], shape=(1,), dtype=int32) tf.Tensor([2], shape=(1,), dtype=int32)
